# Generated by Django 6.0.2 on 2026-02-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('access_code', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('nickname', models.CharField(max_length=25)),
                ('is_placeholder', models.BooleanField(default=True)),
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=250)),
                ('category', models.IntegerField()),
                ('expense_currency', models.CharField(max_length=5)),
                ('amount_in_expenses_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_trip_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='TripApp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_settlement', models.BooleanField(default=False)),
                ('amount_in_cost_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_trip_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_to_settlement_amount_in_cost_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_to_settlement_amount_in_trip_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='TripApp.expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='TripApp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('default_currency', models.CharField(max_length=5)),
                ('trip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementTripCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_main_from', to='TripApp.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_main_to', to='TripApp.participant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripApp.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementOtherCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_other_from', to='TripApp.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_other_to', to='TripApp.participant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripApp.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayments_from', to='TripApp.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayments_to', to='TripApp.participant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripApp.trip')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripApp.trip'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripApp.trip'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('access_code',), name='unique_join_code_when_user_null'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('trip', 'user'), name='unique_user_per_trip'),
        ),
    ]
