# Generated by Django 6.0.2 on 2026-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
