# Generated by Django 6.0.2 on 2026-04-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0006_split_settlement_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receipt', serialize=False, to='TripApp.expense')),
                ('image_data', models.TextField(help_text='Base64-encoded JPEG image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to='TripApp.participant')),
            ],
        ),
    ]
