# Generated by Django 6.0.2 on 2026-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0007_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_hash',
            field=models.CharField(default='', help_text='MD5 hash of image_data — used by clients to detect changes', max_length=32),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
