# Generated by Django 6.0.2 on 2026-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0008_receipt_receipt_hash_receipt_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='settlementhistory',
            name='settlement_type',
            field=models.CharField(choices=[('MANUAL_BY_AMOUNT', 'Manual By Amount'), ('MANUAL_BY_COSTS', 'Manual By Costs'), ('MANUAL_BY_PREPAYMENT', 'Manual By Prepayment'), ('AUTO_PREPAYMENT', 'Auto Prepayment'), ('AUTO_CROSS_SETTLE', 'Auto Cross Settle')], max_length=30),
        ),
    ]
